version: "3.7"

networks:
  laravel-react:

services:
  &db-service laravel-react-mysql:
    container_name: *db-service
    hostname: *db-service
    image: mysql:latest
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: &MYSQL_ROOT_PASS  ${MYSQL_ROOT_PASSWORD}
    networks:
      - laravel-react

  &redis-service laravel-react-redis:
    container_name: *redis-service
    hostname: *redis-service
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    networks:
      - laravel-react

  &php74-fpm laravel-react-fpm:
    container_name: *php74-fpm
    hostname: *php74-fpm
    working_dir: /var/www/html
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    command: php-fpm
    environment:
      FPM_PORT: ${PHP_FPM_PORT}
      FPM_USER: "${CURRENT_USER_ID}"
      FPM_GROUP: "${CURRENT_USER_ID}"
      CURRENT_USER: "${CURRENT_USER}"
      SCHEDULE_PERIOD: 60
    restart: always
    volumes:
      - ./source:/var/www/html
      - ./php-fpm.conf /usr/local/etc/php-fpm.conf
      - ./php.ini /usr/local/etc/php/php.ini
    networks:
      - laravel-react
    depends_on:
      - *db-service
      - *redis-service

  &pma-service laravel-react-pma:
    container_name: *pma-service
    hostname: *pma-service
    image: phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: *db-service
      MYSQL_ROOT_PASSWORD: *MYSQL_ROOT_PASS
      UPLOAD_LIMIT: "1G"
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    depends_on:
      - *db-service
    networks:
      - laravel-react

  &nginx laravel-react-nginx:
    container_name: *nginx
    hostname: *nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: always
    volumes:
      - ./source:/var/www/html
      - ./docker/nginx/conf:/etc/nginx/conf.d/
    ports:
      - ${NGINX_CONTAINER_PORT}:80
    networks:
      - laravel-react
    depends_on:
      - *php74-fpm
      - *db-service
  &node-service laravel-react-node:
    container_name: *node-service
    hostname: *node-service
    restart: on-failure
    user: "1000:1000"
    #    image: node:latest
    build:
      ./docker/node
    networks:
      - laravel-react
    working_dir: /var/www/html
    volumes:
      - ./source:/var/www/html:rw